
apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
  namespace: test
type: Opaque
stringData:
  DATABASE: "<mongo-url>"
  JWT_SECRET: "<key>"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mern-config
  namespace: test
data:
  NODE_ENV: "production"
  PORT: "8888"
  OPENSSL_CONF: "/dev/null"

